added models to work with balance
Yandex-Sirius-Mobile-2023/time_machine pull request #8
Opened 2023-04-13 13:20 UTC by timur-harin

2023-04-13 17:47 UTC, vladcto requested changes
Коменты напиши и удали сгенерированные файлы. А так все норм.

2023-04-13 17:47 UTC, vladcto commented on lib/data/models/account.freezed.dart
Сгенерированные файлы не нужно держать в VCS.

2023-04-13 17:47 UTC, vladcto commented on lib/data/models/portfolio.dart
Не очень понятно почему ```balance``` nullable.
(Если создать приватный констурктор, то можно добавить методы в класс. Так тоже норм, но на будущее)

2023-04-13 17:47 UTC, vladcto commented on lib/data/models/portfolio.freezed.dart
Тоже удали это из индекса.

2023-04-13 17:47 UTC, vladcto commented on lib/data/models/session.dart
Напиши комент к классу, пожалуйста. Я не понимаю, для чего он.

2023-04-13 17:47 UTC, vladcto commented on lib/data/models/session.freezed.dart
Это удалить из индекса.

2023-04-14 11:46 UTC, Khodosov approved these changes

2023-04-14 11:46 UTC, Khodosov commented on lib/data/models/portfolio.dart
> +class Portfolio with _$Portfolio {
Модельки обсудили при встрече. Кажется нужно переписать

2023-04-15 10:57 UTC, merged